import type { Config } from "tailwindcss";

// Design tokens ported from the Material-Design-3 token set used across
// the majority of the original Stitch export (dashboard, problems,
// leaderboard, profile, security, settings, solve). This is the single
// source of truth for color/spacing/typography across the whole app.
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#07006c",
        "on-surface-variant": "#44474c",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d2e4fe",
        "surface-dim": "#dbdad6",
        primary: "#000000",
        "secondary-container": "#6063ee",
        "on-error": "#ffffff",
        "on-primary-container": "#74859d",
        "primary-container": "#0a1d30",
        "on-secondary": "#ffffff",
        "tertiary-container": "#2a1700",
        "surface-bright": "#fbf9f5",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface": "#1b1c1a",
        "secondary-fixed-dim": "#c0c1ff",
        secondary: "#4648d4",
        "on-tertiary-fixed-variant": "#653e00",
        "on-tertiary": "#ffffff",
        "surface-tint": "#4f6076",
        "primary-fixed-dim": "#b6c8e1",
        surface: "#fbf9f5",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-highest": "#e4e2de",
        "on-primary-fixed-variant": "#37485d",
        "on-background": "#1b1c1a",
        error: "#ba1a1a",
        "on-primary-fixed": "#0a1d30",
        "tertiary-fixed-dim": "#ffb95f",
        "on-error-container": "#93000a",
        background: "#fbf9f5",
        "surface-container-high": "#eae8e4",
        tertiary: "#000000",
        outline: "#74777d",
        "inverse-on-surface": "#f2f0ed",
        "secondary-fixed": "#e1e0ff",
        "inverse-primary": "#b6c8e1",
        "outline-variant": "#c4c6cd",
        "surface-container-low": "#f5f3ef",
        "surface-container": "#efeeea",
        "inverse-surface": "#30312e",
        "on-tertiary-container": "#b87500",
        "on-secondary-fixed-variant": "#2f2ebe",
        "tertiary-fixed": "#ffddb8",
        "surface-variant": "#e4e2de",
        "on-secondary-container": "#fffbff",
        "status-easy": "#22c55e",
        "status-medium": "#f59e0b",
        "status-hard": "#ef4444",
        "status-accepted-bg": "rgba(22, 163, 74, 0.1)",
        "status-accepted-text": "#16a34a",
        "status-wrong-bg": "rgba(239, 68, 68, 0.1)",
        "status-wrong-text": "#ef4444",
        "status-tle-bg": "rgba(245, 158, 11, 0.1)",
        "status-tle-text": "#f59e0b",
        "status-solved-bg": "#ecfdf5",
        "status-solved-text": "#10b981",
        "status-notsolved-bg": "#f1f5f9",
        "status-notsolved-text": "#64748b",
        "status-attempted-bg": "#fff7ed",
        "status-attempted-text": "#f97316",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        "2xl": "1rem",
      },
      spacing: {
        "margin-page": "2rem",
        "card-padding": "1.5rem",
        "section-gap": "2rem",
        "stack-gap": "1rem",
        "sidebar-width": "260px",
        gutter: "1.5rem",
        "container-max": "1200px",
      },
      fontFamily: {
        "body-md": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        // label-md/label-sm previously rendered in JetBrains Mono (monospace).
        // Switched to the same Inter font used for body text — monospace is
        // now reserved for the Monaco code editor only.
        "label-md": ["var(--font-inter)"],
        "label-sm": ["var(--font-inter)"],
        "headline-xl": ["var(--font-manrope)"],
        "headline-md": ["var(--font-manrope)"],
        "headline-lg": ["var(--font-manrope)"],
        "headline-xl-mobile": ["var(--font-manrope)"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "16px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["30px", { lineHeight: "38px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-xl-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
      },
      boxShadow: {
        card: "0px 4px 20px rgba(0, 0, 0, 0.04)",
      },
    },
  },
  plugins: [],
};
export default config;
